excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title.html
# We want future posts!
future: true

name: brown-bag.net - Feed your brain
description: A virtual conference held as brown-bags
baseurl: "http://www.brown-bag.net"
repository: "https://github.com/brown-bag/brown-bag.github.com"
view-path: "https://github.com/brown-bag/brown-bag.github.com/blob/master"
edit-path: "https://github.com/brown-bag/brown-bag.github.com/edit/master"

slogantitle: Feed your brain
slogansubtitle: Eat, learn and enjoy

thanks:
  - name: Adam Ralph
    link: "http://adamralph.com"
  - name: David Boike
    link: "http://www.make-awesome.com"
  - name: Mike Minutillo
    link: "http://www.codermike.com"
  - name: Sean Feldman
    link: "http://weblogs.asp.net/sfeldman"
